server:
  port: 8082

spring:
  application:
    name: Study-Japanese
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Japanese?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3086941018Zn
  jackson:
    default-property-inclusion: non_null

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql